CPPFLAGS+=-O0 -g
CPPFLAGS+=-Wall

all: $(ARTIFACT)

OBJS+=klejne.o # application
OBJS+=main_web.o # main/environment
OBJS+=imgui.o imgui_demo.o imgui_draw.o imgui_tables.o imgui_widgets.o # pure imgui deps
OBJS+=imgui_impl_opengl3.o # impl imgui deps

$(ARTIFACT): $(OBJS)
	$(CC) -o $(ARTIFACT) $(OBJS) $(LDFLAGS)

clean:
	rm -f *.o *.wasm $(ARTIFACT)
